### ISSUE TITLE
Cara makenya gimana si ,-

### ISSUE THREAD

**Issue by lawbyte** [salismazaya/komiku_downloader#1]
![Screenshot_20210131-172429.png](https://user-images.githubusercontent.com/35652825/106381106-3c972400-63e9-11eb-8064-6504d8635639.png)
Bro cara makenya gimana si???

**Comment by salismazaya** [comment]
udh saya benerin kaka! silahkan update dan coba lagi

**Comment by salismazaya** [comment]
kalo error pas install Pillow di termux bisa cek ini https://stackoverflow.com/questions/62956054/how-to-install-pillow-on-termux
